### ISSUE TITLE
.mjs files should return text/javascript mime type

### ISSUE THREAD

**Issue by ittayd** [MScholtes/WebServer#1]
.mjs is the extension used for ES6 javascript modules. Modules use strict mime typing, so won't load when application/octet-stream is returned

**Comment by MScholtes** [comment]
Hello ittayd,

I will update the mime type table soon. Until then you might add the entry _**".mjs"="application/javascript";**_ to the hash table **_$MIMEHASH_** in line 70 of **Start-WebServer.ps1** manually.

Greetings

Markus

**Comment by MScholtes** [comment]
Hello ittayd,

updated WebServer to version 1.2.1 today that includes a modified list of mime types including .mjs
