### ISSUE TITLE
POST with body json payload and command execution web form

### ISSUE THREAD

**Issue by ericxin1982** [MScholtes/WebServer#10]
Hi @MScholtes 

That is a great tool.
I have two questions,

As first feature statement said, what is execution and command web form?
And webserver accept post, and how to handle json(json array) body payload inside psp file.

Thanks
Eric Xin

**Comment by MScholtes** [comment]
Hello @ericxin1982,

to see the execution and command web forms, just start the **Powershell Webserver** in a directory without an _index.html_ or _default.html_. Then the example web page appears with links to examples. See screenshot on readme page.

You can send only text parameters with GET or POST methods to psp files. JSON files would have to be text and must be interpreted in custom code in psp file. The other option would be to extend Powershell Webserver.

Greetings

Markus

**Comment by ericxin1982** [comment]
ok
