### ISSUE TITLE
Could not install package 'WebServer 1.0.2' from within Visual Studio

### ISSUE THREAD

**Issue by svetlyobg** [MScholtes/WebServer#2]
Severity	Code	Description	Project	File	Line	Suppression State
Error		Could not install package 'WebServer 1.0.2'. You are trying to install this package into a project that targets '.NETFramework,Version=v4.0', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.

**Comment by MScholtes** [comment]
Hello @svetlyobg,

can this be a misunderstanding? The Powershell Gallery Package **WebServer** is a Powershell module you have to install with _**Install-Module**_ and not with **_Install-Package_**.

Greetings

Markus

**Comment by svetlyobg** [comment]
Ah yes, it is my mistake.
