### ISSUE TITLE
How to get the directory listing

### ISSUE THREAD

**Issue by IAMinZoho** [MScholtes/WebServer#3]
How can I list all the files hosted on the PowerShell based webserver?

**Comment by MScholtes** [comment]
Hello @IAMinZoho,

the default behaviour of the **Powershell Webserver** for the root directory is:
1. present "\index.htm", "\index.html", "\default.htm" or "\default.html" if present
2. present the command menu

You can prevent this completely if you comment out line 172 like this:
```powershell
#		if (($RECEIVED -eq "GET /") -and ($NOIDXFILE)) { $RECEIVED = "GET /command" }
```
Now the **Powershell Webserver** will show a directory listing for the root directory.



In subdirectories there are the folling rules:
1. present "\index.htm", "\index.html", "\default.htm" or "\default.html" if present
2. present the directory listing

You can prevent step 1 wtih changing the filenames in line 573:
```powershell
					$IDXLIST = "/index.htm", "/index.html", "/default.htm", "/default.html"
```

Hope this helps.

Greetings

Markus

**Comment by MScholtes** [comment]
Closed for no response
