### ISSUE TITLE
Binding parameter

### ISSUE THREAD

**Issue by scriptingstudio** [MScholtes/WebServer#5]
`$LISTENER.Prefixes.Add($BINDING)` method requeres a trailing "/" in URL.
```powershell
Exception calling "Add" with "1" argument(s): "Only Uri prefixes ending in '/' are allowed.
Parameter name: uriPrefix"
```

### Fix
`$binding = $binding.trimend('/ ') + '/'`

**Comment by MScholtes** [comment]
Hello @scriptingstudio,

the error messages that Powershell provides are very telling, so I see no reason to cover up a parameter error.

Greetings

Markus

**Comment by scriptingstudio** [comment]
This is reasonable approach
