### ISSUE TITLE
The image  was corrupted after uploading

### ISSUE THREAD

**Issue by fjh1997** [MScholtes/WebServer#7]
Text file is ok,but image file failed.It seems losts some bytes after uploaded.
![image](https://user-images.githubusercontent.com/25281816/218960701-3d08adea-605d-427f-bf12-256ed9796f97.png)

**Comment by MScholtes** [comment]
Hello @fjh1997,

this is too little information to be able to say anything. What kind of browser do you use? Can you check what is missing in the image file (beginning, end or just single bytes in the middle)? What is the file type of the image file?

Greetings

Markus

**Comment by fjh1997** [comment]
> Hello @fjh1997,
> 
> this is too little information to be able to say anything. What kind of browser do you use? Can you check what is missing in the image file (beginning, end or just single bytes in the middle)? What is the file type of the image file?
> 
> Greetings
> 
> Markus

Thanks for reply,I use Microsoft Edge to upload.And the location of the missing bytes is complex, as shown in the pic.It's a png file.og.png is origin file,af.png is the file after uploading.

![image](https://user-images.githubusercontent.com/25281816/219541804-4701cdb6-fd01-4de0-8aea-2e2ef13d4670.png)

**Comment by MScholtes** [comment]
Hello @fjh1997,

I have recreated this with some PNG files, but could not find any error. 
- Does this happen to you with all PNGs or only with the one?
- Can you attach an affected PNG file here so that I can check this?

Greetings

Markus

**Comment by fjh1997** [comment]
@MScholtes 
Thanks for reply，all pngs could be corrupted, here is the examples, both png and jpg could be corrupted.

[examples.zip](https://github.com/MScholtes/WebServer/files/10773917/examples.zip)

**Comment by fjh1997** [comment]
@MScholtes  And I start the webserver in this way
![image](https://user-images.githubusercontent.com/25281816/219854437-6117ce78-00a4-4c95-8b2b-0b679b5027fa.png)
the powershell version is
```
Name                           Value                                                                                                                                                                        
----                           -----                                                                                                                                                                        
PSVersion                      5.1.19041.2364                                                                                                                                                               
PSEdition                      Desktop                                                                                                                                                                      
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}                                                                                                                                                      
BuildVersion                   10.0.19041.2364                                                                                                                                                              
CLRVersion                     4.0.30319.42000                                                                                                                                                              
WSManStackVersion              3.0                                                                                                                                                                          
PSRemotingProtocolVersion      2.3                                                                                                                                                                          
SerializationVersion           1.1.0.1    
```
.net version is 4.0.30319.42000

**Comment by MScholtes** [comment]
Hello @fjh1997,

it happened what I feared: in my environment everything is working fine. I will have to analyze the code in deep, my guess is that it has something to do with the encoding which is surely different in your environment.

Does this error occur everytime? Does this error occur with every PNG file?

Greetings

Markus

**Comment by fjh1997** [comment]
@MScholtes Yeah every png and jpg file could be affected.It seems binary file （zip files，exe files etc）would be corrupted.Thanks.

**Comment by fjh1997** [comment]
> Hello @fjh1997,
> 
> it happened what I feared: in my environment everything is working fine. I will have to analyze the code in deep, my guess is that it has something to do with the encoding which is surely different in your environment.
> 
> Does this error occur everytime? Does this error occur with every PNG file?
> 
> Greetings
> 
> Markus

@MScholtes I have found the reason and make a temporary solution [here](https://github.com/MScholtes/WebServer/compare/master...fjh1997:patch-1?expand=1).
The reason is that the form doesnt have "accept-charset" attribute,so the [HttpListenerRequest.ContentEncoding Property](https://learn.microsoft.com/en-us/dotnet/api/system.net.httplistenerrequest.contentencoding?view=netframework-4.7.2) return a default encoding.
And I have china locale configuration,so  my default encoding is gb2312,which loses data when convert bytes to string.
And in your case, the  default encoding is Windows-1252 ( ISO-8859-1),which is perfect for data conversion,so that no data lose.
Also I have fixed the cjk filename problem in the commit,because cjk filename will usually converted to HTML entity which have a semicolon to make the regex result wrong.

**Comment by MScholtes** [comment]
Hello @fjh1997,

thank you very much for your investigations. I think with my european environment I would never have found this.

I will make some tests and then integrate the changes.

Greetings

Markus

**Comment by MScholtes** [comment]
Hello @fjh1997,

sorry, again it took some time for me to investigate.

I have two questions:
- is it necessary to exchange all occurances of
```powershell
$READER = New-Object System.IO.StreamReader($REQUEST.InputStream, $REQUEST.ContentEncoding)
```
with
```powershell
$READER = New-Object System.IO.StreamReader($REQUEST.InputStream, [System.Text.Encoding]::GetEncoding(1252))
```
to work correctly for you? This expression is used in the script for executing scripts and downloads too.

- I don't really understand the need for the regular expression change from **(.*);** to **(.*?);**. It looks for me as if it leads to truncated filenames in case of a semicolon in it.

Greetings

Markus

**Comment by fjh1997** [comment]
@MScholtes 
For the first question,Yes,In the case of a script with non-ascii characters, if the system default ACP（ $REQUEST.ContentEncoding is actually the system default ACP .In my case is GBK）didn't match the encoding of the non-ascii characters in scripts (for example UTF-8), then garbled encoding will occur.
For the second question,when the file name is in non-ASCII characters, the HTTP request is encoded like this:
```
------WebKitFormBoundaryikLGGK4JsBsnuTue
Content-Disposition: form-data; name="filedata"; filename="&#20013;&#25991;.txt"
Content-Type: text/plain
```
The file name is 中文.txt,but it was encoded to &#20013;&#25991;.txt，that is HmlEntity,has semicolon in it, We should decoded it after uploading.

**Comment by MScholtes** [comment]
Hello @fjh1997,

I released a new version of **WebServer** today where I changed all header encodings to _Windows 1252_.
Additionally I changed the RegEx to the non-greedy version you supplied (after debugging the headers I finally understood the need for this change).

I hope this version is working for you (I cannot test it).

Greetings

Markus

**Comment by fjh1997** [comment]
> Hello @fjh1997,
> 
> I released a new version of **WebServer** today where I changed all header encodings to _Windows 1252_. Additionally I changed the RegEx to the non-greedy version you supplied (after debugging the headers I finally understood the need for this change).
> 
> I hope this version is working for you (I cannot test it).
> 
> Greetings
> 
> Markus

Thanks! Tested with no problems. A nice work!
