### ISSUE TITLE
Can'T download big files >2GB

### ISSUE THREAD

**Issue by sTiReBYJwlYSplALbjGz** [MScholtes/WebServer#8]
I can download smaller files (in megabytes) but not for bigger files /tested with 2.3GB and others

On the logs I see:

 # ... deliver static content
                                                        try {
                                                                $BUFFER = [System.IO.File]::ReadAllBytes($CHECKFILE)
                                                                $RESPONSE.ContentLength64 = $BUFFER.Length
                                                                $RESPONSE.SendChunked = $FALSE
                                                                if ($MIMEHASH.ContainsKey($EXTENSION))
                                                                { # known mime type for this file's extension available
                                                                        $RESPONSE.ContentType = $MIMEHASH.Item($EXTENSION)
                                                                }
                                                                else
                                                                { # no, serve as binary download
                                                                        $RESPONSE.ContentType = "application/octet-stream"
                                                                        $FILENAME = Split-Path -Leaf $CHECKFILE
                                                                        $RESPONSE.AddHeader("Content-Disposition", "attachment; filename=$FILENAME")
                                                                }
                                                                $RESPONSE.AddHeader("Last-Modified", [IO.File]::GetLastWriteTime($CHECKFILE).ToString('r'))
                                                                $RESPONSE.AddHeader("Server", "Powershell Webserver/1.5 on ")
                                                                $RESPONSE.OutputStream.Write($BUFFER, 0, $BUFFER.Length)
                                                                # mark response as already given
                                                                $RESPONSEWRITTEN = $TRUE
                                                        }
                                                        catch
                                                        {
                                                                # just ignore. Error handling comes afterwards since not every error throws an exception
                                                        }
                                                        if ($Error.Count -gt 0)
                                                        { # retrieve error message on error
                                                                $RESULT = "`nError while downloading '$CHECKFILE'`n`n"
                                                                $RESULT += $Error[0]
                                                                $Error.Clear()
                                                        }

**Comment by MScholtes** [comment]
Hello @sTiReBYJwlYSplALbjGz,

you can see the following comment in the readme:

**Download / Upload of large files**
There is no optimization for large file download or uploads (no chunking or similiar techniques). The transfer of large files might work, or might not.

The reason for this is that it is very time-consuming to write the routines for a web server that catches all possible cases for a download of files (size of files, parts of files, bandwidth limit...).
This is beyond the effort I can put into this project.

Sorry for that.

Markus

**Comment by MScholtes** [comment]
Closed for no reaction
